export const ALL_COUNTRIES_REQUEST = "ALL_COUNTRIES_REQUEST";
export const ALL_COUNTRIES_SUCCESS = "ALL_COUNTRIES_SUCCESS";
export const ALL_COUNTRIES_FAIL = "ALL_COUNTRIES_FAIL";
export const ALL_COUNTRIES_RESET = "ALL_COUNTRIES_RESET";

export const COUNTRY_REQUEST = "COUNTRY_REQUEST";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";
export const COUNTRY_FAIL = "COUNTRY_FAIL";
export const COUNTRY_RESET = "COUNTRY_RESET";

//
